//
//  Tree.h
//  ProjectName
//
//  Created by NZ on 20.07.2021.
//  Copyright © 2021 NZ. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//
//  This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
//

#import <UIKit/UIKit.h>



typedef NS_ENUM(NSInteger, TreeResizingBehavior)
{
    TreeResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    TreeResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    TreeResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    TreeResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

};

extern CGRect TreeResizingBehaviorApply(TreeResizingBehavior behavior, CGRect rect, CGRect target);


@interface Tree : NSObject

//// In Trial version of PaintCode, the code generation is limited to 3 canvases.

// Drawing Methods
+ (void)drawTreeCanvas;
+ (void)drawTreeCanvasWithFrame: (CGRect)targetFrame resizing: (TreeResizingBehavior)resizing;

@end
